apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: zerodowntime
spec:
  host: zerodowntime
  subsets:
  - name: primary
    labels:
      version: v1
  - name: canary
    labels:
      version: v2
