apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: practice
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: practice2
        image: mysql:8.0.22
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_ROOT_PASSWORD
          value: pass
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: practice
  labels:
    app: db
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: db-port
  selector:
    app: db
  type: ClusterIP