apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice2-v1
  namespace: practice
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice2
      version: v1
  template:
    metadata:
      labels:
        app: practice2
        version: v1
    spec:
      containers:
      - name: practice2
        image: docker.io/gortazar/flyway:v1 #Ours image that need to pull on dockerhub
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9991
        env:
        - name: MYSQL_HOST
          value: "db"
        - name: SERVER_PORT
          value: "9991"
        - name: SPRING_FLYWAY_VALIDATE-ON-MIGRATE
          value: "false"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://db:3306/test"
---
apiVersion: v1
kind: Service
metadata:
  name: practice2
  namespace: practice
  labels:
    app: practice2
spec:
  ports:
  - port: 9991
    name: http
  selector:
    app: practice2