apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.22
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pass
            - name: MYSQL_DATABASE
              value: test
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: book-app
  labels:
    app: book-app
spec:
  ports:
  - port: 3306
    name: tcp
    targetPort: 3306
    protocol: TCP
  selector:
    app: book-app
