apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapp-v3
  labels:
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookapp
      version: v3
  template:
    metadata:
      labels:
        app: bookapp
        version: v3
    spec:
      containers:
      - name: bookapp
        image: docker.io/juablazmahuerta/book-app:v3
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        env:
          - name: MYSQL_HOST
            value: db
          - name: MYSQL_DB
            value: test
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASS
            value: pass
          - name: SERVER_PORT
            value: "9991"
          - name: SPRING_FLYWAY_VALIDATE-ON-MIGRATE
            value: "false"
        ports:
          - containerPort: 9991

---
apiVersion: v1
kind: Service
metadata:
  name: bookapp
  labels:
    app: bookapp
spec:
  ports:
  - port: 9991
    name: http
  selector:
    app: bookapp
