apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app-v1
  namespace: practice
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-app
      version: v1
  template:
    metadata:
      labels:
        app: book-app
        version: v1
    spec:
      containers:
      - name: book-app
        image: docker.io/juablazmahuerta/book-app:v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 9991
        env:
        - name: MYSQL_HOST
          value: "db-flyway"
        - name: SERVER_PORT
          value: "9991"
        - name: MYSQL_DB
          value: test
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASS
          value: pass
        securityContext:
            allowPrivilegeEscalation: false

---
apiVersion: v1
kind: Service
metadata:
  name: book-app
  namespace: practice

  labels:
    app: book-app
spec:
  ports:
  - port: 9991
    name: http
  selector:
    app: book-app
